# Generated by Django 4.2.5 on 2023-09-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('path', models.TextField()),
                ('hash', models.TextField()),
                ('parent', models.TextField(null=True)),
            ],
            options={
                'db_table': 'heading',
            },
        ),
    ]
